spring:
  datasource:
    url: jdbc:postgresql://yamabiko.proxy.rlwy.net:19456/railway
    username: postgres
    password: WFzfMKqisEwCMxdJfNPSuVHjfFPtpEKy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
